Update Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
OWASP/CheatSheetSeries pull request #1015
Opened 2022-12-03 10:13 UTC by jonathan-jaffe-lmnd

Grammatical corrections and improved readability.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

2022-12-15 16:50 UTC, szh requested changes
Mostly good, just left a few nit comments.

2022-12-15 16:50 UTC, szh commented on cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
> +This is the implementation of the utility class that generates the the identifier to use for an exchange with the front-end:
```suggestion
This is an implementation of the utility class that generates the identifier to use for an exchange with the front-end:
```

2022-12-15 16:50 UTC, szh commented on cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
> +- Allows the absence of a mapping table—-real ID vs front-end ID—-in user session or application level caches.
```suggestion
- Allows the absence of a mapping table (real ID vs front-end ID) in user session or application level caches.
```
I think parenthesis is a bit clearer.

2022-12-15 16:50 UTC, szh commented on cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
> +**I**nsecure **D**irect **O**bject **R**eference (called **IDOR** from here) occurs when a application exposes a reference to an internal implementation object. Using this method, an IDOR reveals the
```suggestion
**I**nsecure **D**irect **O**bject **R**eference (called **IDOR** from here) occurs when a application exposes a reference to an internal implementation object. Using this method, an IDOR reveals the real identifier and format or pattern used of the element in the storage backend. The most common example is of a record identifier in a storage system such as a database or filesystem, though these are not the only examples.
```
There's a trailing space that's causing the lint action to fail.

2023-01-02 14:49 UTC, mackowski commented
Hey @jonathan-jaffe-lmnd can you fix lint errors?

2023-01-02 22:08 UTC, jmanico approved these changes

2023-01-02 22:09 UTC, merged