Initial start for prototype pollution prevention cheatsheet
OWASP/CheatSheetSeries pull request #1157
Opened 2023-06-25 13:26 UTC by tghosth

2023-06-25 17:43 UTC, jmanico submitted a review, later dismissed
Looking good so far, you can also start in the staging directory if you want more rapid commits https://github.com/OWASP/CheatSheetSeries/tree/master/cheatsheets_draft

2023-06-26 07:33 UTC, tghosth commented
Thanks @jmanico, I think this will do for now and then people add to it as they see fit. The important thing is that the information was captured.

2023-06-26 18:58 UTC, tghosth commented
@jmanico can you now merge it?

2023-06-29 17:22 UTC, tghosth commented
Any chance this can now be merged @szh @jmanico ?

2023-06-29 18:14 UTC, szh requested changes
Two nits. Also should we include examples of what not to do, and show example exploits? Even just one simple example would be helpful for understanding the danger.

2023-06-29 18:14 UTC, szh commented on cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.md
> +Node.js also offers the ability to remove the `__proto__` property completely using the `--disable-proto=delete` flag. Note this is a defence in depth measure.
Let's keep spellings consistent with US English
```suggestion
Node.js also offers the ability to remove the `__proto__` property completely using the `--disable-proto=delete` flag. Note this is a defense in depth measure.
```

2023-06-29 18:14 UTC, szh commented on cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.md
> +Prototype pollution is still possible using constructor.prototype properties but removing `__proto__` helps reduce attack surface and prevent certain attacks.
```suggestion
Prototype pollution is still possible using `constructor.prototype` properties but removing `__proto__` helps reduce attack surface and prevent certain attacks.
```

2023-06-30 17:02 UTC, merged

2023-07-03 09:35 UTC, tghosth commented on cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.md
> +Prototype pollution is still possible using constructor.prototype properties but removing `__proto__` helps reduce attack surface and prevent certain attacks.
Fixed in #1161