Fix grammar in Microservices Security Cheat Sheet
OWASP/CheatSheetSeries pull request #1194
Opened 2023-09-05 14:49 UTC by JefSchraag

2023-09-05 14:53 UTC, szh requested changes
Overall looks great, just one comment

2023-09-05 14:53 UTC, szh commented on cheatsheets/Microservices_Security_Cheat_Sheet.md
> +To validate incoming tokens, the microservice invokes a centralized service token service via network call.
I think these should be formatted as a list.

2023-09-05 15:40 UTC, JefSchraag commented on cheatsheets/Microservices_Security_Cheat_Sheet.md
> -6. Access control policy formal procedures like development, approval, rolling-out must be implemented.
That was a mistake. The points are added again.

2023-09-05 16:06 UTC, szh commented
Awesome, looks great. There are two lint errors: 
>  33:302  ✓ error  Incorrect usage of the term: “end-user”, use “end user” instead  terminology
  84:315  ✓ error  Incorrect usage of the term: “end-user”, use “end user” instead  terminology

2023-09-06 12:34 UTC, mackowski approved these changes

2023-09-06 13:17 UTC, szh approved these changes
LGTM

2023-09-06 13:18 UTC, merged