Update Multifactor_Authentication_Cheat_Sheet.md
OWASP/CheatSheetSeries pull request #1248
Opened 2023-12-05 21:26 UTC by Brianthered

Updated biometric information, as it has become commonly available through webauthn.  I think it would make sense to add a cheatsheet on webauthn, but I didn't want to be presumptive.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as `[TEXT](URL)`
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

2023-12-05 21:40 UTC, szh requested changes
Thank you for your contribution!
I agree that this should be updated. But I'm not sure biometrics and webauthn should be used interchangeably. WebAuthn supports many factors that aren't biometric. If we're going to update this, which I think we should, we need to be clear to avoid any confusion.

2023-12-06 05:18 UTC, jmanico approved these changes

2023-12-06 05:19 UTC, jmanico commented
Good fix, pushing this live

2023-12-06 05:20 UTC, merged

2024-01-11 16:22 UTC, shoeper commented on cheatsheets/Multifactor_Authentication_Cheat_Sheet.md
> +The final factor in the traditional view of MFA is something you are - which is one of the physical attributes of the users (often called biometrics). Biometrics has been rarely used in web pages due
have