Update Authentication_Cheat_Sheet.md
OWASP/CheatSheetSeries pull request #1280
Opened 2024-01-12 13:21 UTC by aiacobelli2

I've tried to add/correct the first 4 titles.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as `[TEXT](URL)`
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

2024-01-15 17:34 UTC, aiacobelli2 commented
> I'm a little concerned that this is too jargony. Cheat Sheets are meant to be easy to read and understand and I'm afraid this will be too hard for beginners to parse.

I understand, but I've seen lot's of Appsec beginners not understanding the basic difference between identification, authentication, digital identity, and identity proofing. This basic misconception makes them not understand how to propperly think about the subject. 

The same about user-ids and usernames.

2024-01-16 09:57 UTC, szh commented
I do understand the concern, but I think we need to have a way of explaining the difference in a way that beginners can understand. This may be a matter of using simple language and the like.

2024-01-21 21:35 UTC, otkd requested changes
@aiacobelli2 Agree conceptually with your changes, but simplified for intended audience as @szh noted

2024-01-21 21:35 UTC, otkd commented on cheatsheets/Authentication_Cheat_Sheet.md
> +**Identity Proofing** establishes that a subject is actually who they claim to be. This concept is related to KYC concepts and it aims to bind a digital identity with a real person.
```suggestion
```

Too detailed for audience

2024-01-21 21:35 UTC, otkd commented on cheatsheets/Authentication_Cheat_Sheet.md
> +**Authentication** is the process of determining the validity of one or more authenticators used to claim a digital identity. Authentication establishes that a subject attempting to access a digital
```suggestion
**Authentication** is the process of verifying that an individual, entity, or website is who or what it claims to be by determining the validity of one or more authenticators (like passwords, fingerprints, or security tokens) that are used to back up this claim.
```

2024-01-24 14:12 UTC, szh commented
@otkd I like your suggestions. @aiacobelli2 would you like to incorporate them and update the PR?

2024-01-28 10:25 UTC, jmanico commented
> > I'm a little concerned that this is too jargony. Cheat Sheets are meant to be easy to read and understand and I'm afraid this will be too hard for beginners to parse.
> 
> I understand, but I've seen lot's of Appsec beginners not understanding the basic difference between identification, authentication, digital identity, and identity proofing. This basic misconception makes them not understand how to properly think about the subject. The same about user id's and usernames.
> 
> For example, in this cheat-sheet appears Oauth as an authentication framework and this is just wrong.

Your comment about OAuth is spot on, thank you for catching this!

2024-01-28 10:27 UTC, jmanico commented
These changes are super important. We have big mistakes regarding how we define these core terms and I totally support this work. Thank you everyone!

2024-01-28 16:40 UTC, otkd commented on cheatsheets/Authentication_Cheat_Sheet.md
> +**Authentication** is the process of determining the validity of one or more authenticators used to claim a digital identity. Authentication establishes that a subject attempting to access a digital
Updated suggestion to include `(**AuthN**)`

2024-01-30 12:10 UTC, jmanico approved these changes

2024-01-30 12:11 UTC, jmanico commented
There are a few lint errors in the markup. Can you kindly fix those? I'll merge this soon after they are fixed.

2024-01-30 14:45 UTC, szh requested changes
@jmanico I think we should wait to merge this until @otkd's suggestions are implemented.

2024-01-30 15:00 UTC, jmanico commented
> @jmanico I think we should wait to merge this until @otkd's suggestions are implemented.

You got it, I have a quick trigger-finger to merge, but I will wait! :)

2024-02-08 12:09 UTC, jmanico approved these changes

2024-02-08 12:10 UTC, jmanico commented
There are a few lint errors here but we are getting close!

2024-02-08 14:54 UTC, otkd requested changes

2024-02-08 14:54 UTC, otkd commented on cheatsheets/Authentication_Cheat_Sheet.md
> +Usernames are easy-to-remember identifiers chosen by the user and used for identifying themselves when logging into a system or service. The terms User ID and username might be used interchangeably i
```suggestion
Usernames are easy-to-remember identifiers chosen by the user and used for identifying themselves when logging into a system or service. The terms User ID and username might be used interchangeably if the username chosen by the user also serves as their unique identifier within the system.
```

Should resolve mdlint check

2024-02-14 14:02 UTC, merged