Transport_Layer_Security_Cheat_Sheet.md: updated section on Diffie-Hellman parameters
OWASP/CheatSheetSeries pull request #1455
Opened 2024-07-25 09:23 UTC by nmav

This PR covers issue #1453.

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as `[TEXT](URL)`
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

2024-07-26 00:18 UTC, kwwall requested changes
Some minor changes requested.

2024-07-26 00:18 UTC, kwwall commented on cheatsheets/Transport_Layer_Security_Cheat_Sheet.md
> +Whereas in the past the TLS protocol required to set Diffie-Hellman parameters for use by the ephemeral Diffie-Hellman key exchange (signified by the "DHE" or "EDH" strings in the cipher suite name),
Word missing (presumably 'it' or perhaps 'the client') in the clause "meaning could only unconditionally accept or drop".

2024-07-26 00:18 UTC, kwwall commented on cheatsheets/Transport_Layer_Security_Cheat_Sheet.md
> +Diffie-Hellman groups are `ffdhe2048`, `ffdhe3072`, `ffdhe4096`, `ffdhe6144`, `ffdhe8192` as specified in RFC7919.
Add link for the RFC.

2024-07-26 00:18 UTC, kwwall commented on cheatsheets/Transport_Layer_Security_Cheat_Sheet.md
> +By default openssl 3.0 enables all the above groups. To modify them ensure that the right ffdhe parameters are present in `openssl.conf`. For example
The term "ffdhe" in this sentence should probably be formatted as `code` or placed in quotes.

Also, the Linux manual page for _openssl_(1) refers to "openssl.cnf" rather than "openssl.conf". YMMV on other OSes. There is an environment variable (**OPENSSL_CONF**) which is perhaps what caused the confusion. For example, on Linux Mint, it's under **/etc/ssl/openssl.cnf**.

2024-07-26 06:40 UTC, nmav commented
> Some minor changes requested.

Thanks, very good suggestions. I've updated the text to address the suggestions. Let me know if there is anything remaining.

2024-07-26 06:42 UTC, nmav commented
For the title of the section I realize that the current one is a negative one. An alternative suggestion would be:
 * Set the appropriate Diffie-Hellman groups

2024-07-26 14:13 UTC, kwwall submitted a review, later dismissed
Approve all my requested changes. I agree with the change you suggested for the section title. Please do change it from "Do not explicitly set Diffie-Hellman Paramters" to "Set the appropriate Diffie-Hellman groups". Otherwise, LGTM.

2024-07-31 12:31 UTC, jmanico approved these changes
This overall seems reasonable. Hey @kwwall would you like to take a look?

2024-07-31 12:37 UTC, kwwall commented
Already looked at this and requested changes and after those changes looked
again and approved them. That should show up unless those commits were
deleted.

On Wed, Jul 31, 2024, 8:31 AM Jim Manico ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> This overall seems reasonable. Hey @kwwall <https://github.com/kwwall>
> would you like to take a look?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/CheatSheetSeries/pull/1455#pullrequestreview-2210037490>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAO6PG7BQ4H53ZYBBNL2HATZPDKLHAVCNFSM6AAAAABLOEIPD6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMJQGAZTONBZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-02 09:43 UTC, nmav commented
Any change needed from my part?

2024-08-03 19:29 UTC, kwwall approved these changes
LGTM. All my nits have been addressed.

2024-08-03 19:36 UTC, merged