General Markdown Maintenance & Addition of Dockerfile for Easy Testing w/o Python
OWASP/CheatSheetSeries pull request #1459
Opened 2024-07-31 17:02 UTC by Jeymz

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [X] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [X] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [X] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [X] All your assets are stored in the **assets** folder.
- [X] All the images used are in the **PNG** format.
- [X] Any references to websites have been formatted as `[TEXT](URL)`
- [X] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue N/A.

Thank you again for your contribution :smiley:

2024-07-31 17:15 UTC, szh approved these changes
I'm super excited about this. Should make things smoother for the upcoming bug bash (#1451). Docker workflow works great.

2024-08-01 07:07 UTC, mackowski commented
I think that changes in the CODEOWNERS file will not work. GitHub also shows the notice about that in the PR
<img width="322" alt="Screenshot 2024-08-01 at 09 06 21" src="https://github.com/user-attachments/assets/fa8c852d-6286-4419-bd2d-97690bb1b3dd">

2024-08-01 07:07 UTC, mackowski requested changes
I think that changes in the CODEOWNERS file will not work. GitHub also shows the notice about that in the PR
<img width="322" alt="Screenshot 2024-08-01 at 09 06 21" src="https://github.com/user-attachments/assets/fa8c852d-6286-4419-bd2d-97690bb1b3dd">

2024-08-03 17:37 UTC, jmanico commented
Even though checks passed @mackowski still has concerns that seem very reasonable. What is next?

2024-08-05 13:45 UTC, szh commented
I tried to push a commit that removes the section of the CODEOWNERS file with the error, but I'm getting "permission denied" despite the "Maintainers are allowed to edit this pull request" setting. @Jeymz can you take care of it instead?

2024-08-05 13:45 UTC, szh commented on .github/CODEOWNERS
> +
```suggestion
```

2024-08-05 13:46 UTC, szh commented
Hmm, it seems I can do it from the web interface

2024-08-05 13:47 UTC, szh approved these changes

2024-08-07 16:03 UTC, Jeymz commented
Sorry for the lack of response. I don't regularly check github since it's not my primary working repository. It looks like Shlomo was able to resolve the issues. This was not an issue with the update but was an issue with an outdated entry that was still included in the codeowners I believe. Should probably warrant a regular review of those permissions.

2024-08-07 16:05 UTC, merged