PHP cheat sheet updates.
OWASP/CheatSheetSeries pull request #1464
Opened 2024-08-07 21:04 UTC by ChaseOnTheWeb

* Replace mentions of PHP 7 (now EOL) with a link to check the current supported version of PHP.
* Remove `safe_mode` mention, it was removed in PHP 5.4.
* Remove `track_errors` ini option, which is removed from PHP 8.
* Remove Suhosin/Suhosin-ng mentions.

This PR covers issue #1449.

# You're A Rockstar

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series.

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as `[TEXT](URL)`
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #`<REPLACE WITH ISSUE NUMBER>`.

Thank you again for your contribution :smiley:

2024-08-07 21:17 UTC, szh approved these changes
I'm not familiar with PHP but this LGTM

2024-08-08 08:15 UTC, glye requested changes
Thank you very much for the PR! One crucial feedback about ignore args, and one less important one about vendor support.

2024-08-08 08:15 UTC, glye commented on cheatsheets/PHP_Configuration_Cheat_Sheet.md
> +You should be running a [supported version of PHP](https://www.php.net/supported-versions.php) (as of this writing, 8.1 is the oldest version receiving security support). Review the [core `php.ini` d
```suggestion
You should be running a [supported version of PHP](https://www.php.net/supported-versions.php) (as of this writing, 8.1 is the oldest version receiving security support from PHP, though distribution vendors often provide extended support). Review the [core `php.ini` directives](https://www.php.net/manual/ini.core.php) in the PHP Manual for a complete reference on every value in the `php.ini` configuration file.
```

2024-08-08 08:15 UTC, glye commented on cheatsheets/PHP_Configuration_Cheat_Sheet.md
> +zend.exception_ignore_args = Off
```suggestion
zend.exception_ignore_args = On
```
0/Off (disabled) is the default value. 1/On (enabled) means arguments will be excluded from stack traces.
https://www.php.net/manual/en/ini.core.php#ini.zend.exception-ignore-args

2024-08-08 08:23 UTC, jmanico approved these changes

2024-08-08 08:23 UTC, merged

2024-08-08 08:59 UTC, glye commented
Since this was merged, I put my review feedback in a new PR: https://github.com/OWASP/CheatSheetSeries/pull/1475