Update Forgot_Password_Cheat_Sheet.md
OWASP/CheatSheetSeries pull request #1553
Opened 2024-12-03 16:01 UTC by gl4nce

- removed section about backup codes from CS because it's out of scope
- added hint for MFA recovery methods with link to corresponding CS

This PR fixes issue #1538.

2024-12-06 00:06 UTC, jmanico reviewed
Should we also mention that these codes should be random?

2024-12-06 05:42 UTC, kwwall requested changes
I'm fine with the general direction you are taking this, but can we please link to the specific section on "[MFA Recovery](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Multifactor_Authentication_Cheat_Sheet.md#resetting-mfa)" instead of just the general MFA CS?

2024-12-06 05:44 UTC, kwwall commented
> Should we also mention that these codes should be random?

Yes, but in the MFA Reset section rather than here.

2024-12-09 16:01 UTC, mackowski approved these changes

2024-12-20 03:58 UTC, kwwall approved these changes
LGTM

2024-12-20 10:59 UTC, merged