Incorporated feedback as discussed with Jeroen
OWASP/CheatSheetSeries pull request #842
Opened 2022-02-01 13:49 UTC by DrRetsiemsuah

## Structure

**Section 2**
- Merged "Remove Human Interaction" (2.4) with 2.8 to "2.4 Automate Secrets Management"
- Merge "Use Least Privilege (2.4)" with 2.3 to "2.3 Access Controls"

**Section 4**
- Added TCBs for additional secret storage services from Cloud providers
    - AWS Nitro Enclaves
    - AWS CloudHSM
    - Google Cloud Confidential Computing
    - Azure Confidential Computing
    - Azure Dedicated HSM 

## Content
**Section 2.6.2**
- Added exclusion for user credentials according to e.g. NIST guidelines nowadays suggest that passwords should only be rotated, if there is evidence for compromise ([NIST Special Publication 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#:~:text=Do%20not%20require%20that%20memorized%20secrets%20be%20changed%20arbitrarily%20(e.g.%2C%20periodically)%20unless%20there%20is%20a%20user%20request%20or%20evidence%20of%20authenticator%20compromise.%20(See%20Section%205.1.1%20for%20additional%20information)))

**Section 2.11**
- Added metadata “By whom it was created/consumed/archived/rotated/deleted” (referring to Auditing requirements)

**Section 3.2**
- Added GCP Secret Manager ([Secret Manager | Google Cloud](https://cloud.google.com/secret-manager))

2022-02-01 13:55 UTC, commjoen commented
Maybe we can do this one after https://github.com/OWASP/CheatSheetSeries/pull/841 so we can do this in steps?

2022-02-09 16:09 UTC, mackowski commented
This now have conflicts, please fix the conflicts.

2022-02-13 03:22 UTC, commjoen requested changes
Can you please first resolve the conflicts and make sure there is the right content at the todos?

2022-02-13 03:22 UTC, commjoen commented on cheatsheets_draft/Secrets_Management_CheatSheet.md
> +- TODO: https://aws.amazon.com/cloudhsm/
Maybe for now first detail/fill in the todos before this gets merged?

2022-02-13 03:22 UTC, commjoen commented on cheatsheets_draft/Secrets_Management_CheatSheet.md
> +- TODO: https://aws.amazon.com/ec2/nitro/nitro-enclaves/
Maybe for now first detail/fill in the todos before this gets merged?

2022-02-13 03:22 UTC, commjoen commented on cheatsheets_draft/Secrets_Management_CheatSheet.md
> +TODO: https://cloud.google.com/confidential-computing
Maybe for now first detail/fill in the todos before this gets merged?

2022-02-13 03:22 UTC, commjoen commented on cheatsheets_draft/Secrets_Management_CheatSheet.md
> +
Maybe for now first detail/fill in the todos before this gets merged?

2022-02-13 03:22 UTC, commjoen commented on cheatsheets_draft/Secrets_Management_CheatSheet.md
> +TODO: https://azure.microsoft.com/en-us/services/azure-dedicated-hsm/
Maybe for now first detail/fill in the todos before this gets merged?

2022-02-15 08:27 UTC, DrRetsiemsuah commented
@commjoen I'll work on resolving the todos later this week and update the PR

2022-02-18 13:17 UTC, closed without merging