Update HTTP Security Response Headers Cheat Sheet
OWASP/CheatSheetSeries pull request #995
Opened 2022-10-17 15:39 UTC by fcanogab

Update HTTP Security Response Headers Cheat Sheet to provide to developers up-to-date information about when a header is recommended and the impact of using.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #991 

Thank you again for your contribution :smiley:

2022-11-27 09:13 UTC, righettod commented
Hi,

Feel free to also make a ref to the [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/) 😃 

Dom

2022-12-20 14:48 UTC, mwjcomputing commented
This looks great. Awesome job.

2022-12-23 14:29 UTC, szh requested changes
I didn't have time to review the content thoroughly yet, but I added some suggestions for spelling and grammar.

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +Content Security Policy (CSP) frame-ancestors directive obsoletes X-Frame-Options for supporting browsers [source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).
```suggestion
Content Security Policy (CSP) frame-ancestors directive obsoletes X-Frame-Options for supporting browsers ([source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)).
```

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +This header is used to block browsers [MIME type sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#mime_sniffing), which can transform non-executable MIME types in
```suggestion
This header is used to block browsers' [MIME type sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#mime_sniffing), which can transform non-executable MIME types into executable MIME types ([MIME Confusion Attacks](https://blog.mozilla.org/security/2016/08/26/mitigating-mime-confusion-attacks-in-firefox/)).
```

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +Set the Content-Type header correctly through the site.
```suggestion
Set the Content-Type header correctly throughout the site.
```

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +Not use it. Mozilla [recommends](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT) avoiding it, and removing it from existing code if possible.
```suggestion
Do not use it. Mozilla [recommends](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT) avoiding it, and removing it from existing code if possible.
```

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +Content Security Policy (CSP) is a security feature that is used to specify the origin of content that is allowed to be loaded on a website or in a web applicationis. It is an added layer of security
```suggestion
Content Security Policy (CSP) is a security feature that is used to specify the origin of content that is allowed to be loaded on a website or in a web applications. It is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement to distribution of malware.
```

2022-12-23 14:29 UTC, szh commented on cheatsheets/HTTP_Headers_Cheat_Sheet.md
> +If you don't use this header, your site is protected by default by the Same Origin Policy (SOP). What this header does is relaxing this control in specified circumstances.
```suggestion
If you don't use this header, your site is protected by default by the Same Origin Policy (SOP). What this header does is relax this control in specified circumstances.
```

2022-12-23 15:16 UTC, jmanico approved these changes

2022-12-23 15:18 UTC, jmanico requested changes
Use a Content Security Policy (CSP) that disables the use of inline JavaScript ('unsafe-inline').

unsafe-inline actually disables this protection, can you please remove that portion?

2023-01-02 22:12 UTC, merged